version: '3.8'

# Version von Image "Cassandra" ist in .env-Datei definiert

services:
  cassandra-1:
    image: cassandra:${CASSANDRA_VERSION}
    container_name: microblogging-cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=MicrobloggingCluster
      - CASSANDRA_DC=rechenzentrum1 # DC: Data Center (Rechenzentrum)
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=8 # Anzahl virtuelle Knoten (vNodes)
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"   # CQL native transport port
    networks:
      - cassandra-netzwerk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-2:
    image: cassandra:${CASSANDRA_VERSION}
    container_name: microblogging-cassandra-2
    environment:
      - CASSANDRA_CLUSTER_NAME=MicrobloggingCluster
      - CASSANDRA_DC=rechenzentrum1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9043:9042"
    depends_on:
      cassandra-1:
        condition: service_healthy
    networks:
      - cassandra-netzwerk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  cassandra-netzwerk:
    driver: bridge
