version: '3.8'

# CASSANDRA-Version ist in .env-Datei definiert

services:
  cassandra-1:
    image: cassandra:${CASSANDRA_VERSION}
    container_name: microblogging-cassandra-1
    environment:
      - CASSANDRA_CLUSTER_NAME=MicrobloggingCluster
      - CASSANDRA_DC=rechenzentrum1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9042:9042"   # CQL native transport port
    networks:
      - netzwerk-intern   # für Datenaustausch zwischen den Cassandra-Knoten
      - netzwerk-extern   # Für externen Zugriff
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  cassandra-2:
    image: cassandra:${CASSANDRA_VERSION}
    container_name: microblogging-cassandra-2
    environment:
      - CASSANDRA_CLUSTER_NAME=MicrobloggingCluster
      - CASSANDRA_DC=rechenzentrum1
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_SEEDS=cassandra-1
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
    ports:
      - "9043:9042"
    depends_on:
      cassandra-1:
        condition: service_healthy
    networks:
      - netzwerk-intern  # For inter-node communication
      - netzwerk-extern  # For external client access
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # cassandra-web:
  #   image: ipushc/cassandra-web:latest
  #   container_name: microblogging-cassandra-web
  #   environment:
  #     - CASSANDRA_HOST_IPS=cassandra-1
  #     - CASSANDRA_PORT=9042
  #     - CASSANDRA_USERNAME=
  #     - CASSANDRA_PASSWORD=
  #   depends_on:
  #     cassandra-1:
  #       condition: service_healthy
  #   ports:
  #     - "3000:8083"
  #   networks:
  #     - cassandra-1-network
  #     - cassandra-2-network

networks:
  netzwerk-intern:
    driver: bridge
  netzwerk-extern:
    driver: bridge
